
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rafae
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    int CuentaBoton=0;
    int turno=1;
    int tipo=0;
    Datos datos1;
    Datos datos2;
    String puntos;
    
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("objetivo.png")));
         Datos datosJug1 = new Datos();
         Datos datosJug2= new Datos();
         this.datos1=datosJug1;
         this.datos2=datosJug2;
    }
    
    public int Acierto(){
        int res=0;
        String iconoUsar="dardo.png";
        ImageIcon icono = new ImageIcon(iconoUsar);
        Object[] opciones = {"Simple","Doble","Triple"};
        int pos=JOptionPane.showOptionDialog(rootPane, "Elige:", "Acierto", WIDTH, HEIGHT, icono, opciones, EXIT_ON_CLOSE);
        
        if(pos==0){
        res=1;
        }else if(pos==1){
        res=2;
        }else{
        res=3;
        }
        
        return res;
    }
    
    //metodos varios para sumar y obtener el puntaje
    public String obtencionPuntos(){
    String puntaje=  JOptionPane.showInputDialog(rootPane,"En que numero marcaste?", "Numero", HEIGHT);
    return puntaje;
    }
    
    public void sumar1(String puntos){
        datos1.setPuntaje(datos1.getPuntaje()+Integer.valueOf(puntos));
    }
    
    public void sumar2(String puntos){
        datos2.setPuntaje(datos2.getPuntaje()+Integer.valueOf(puntos));
    }
        //activa botones y comprueba el ganador cuando se dan las condiciones propicias
    public void activarBotones(){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jLabel4.setText(Integer.toString(turno));
            
            if(turno==20){
           
            this.setVisible(false);
         String iconoUsar="trofeo.png";
         ImageIcon icono = new ImageIcon(iconoUsar);
        if(datos1.getPuntaje()>datos2.getPuntaje()){
            JOptionPane.showMessageDialog(null, "El ganador es "+jLabel2.getText()+"!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }else if(datos1.getPuntaje()<datos2.getPuntaje()){
        JOptionPane.showMessageDialog(null, "El ganador es "+jLabel3.getText()+"!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }else{
        JOptionPane.showMessageDialog(null, "Empate!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }
        this.dispose();
        
            }
        //comprobacion de ganar segun si estan cerrados o no
            if(datos1.tablero[0]==3&&datos1.tablero[1]==3&&datos1.tablero[2]==3&&datos1.tablero[3]==3&&datos1.tablero[4]==3&&datos1.tablero[5]==3&&datos1.tablero[6]==3&&
               datos2.tablero[0]==3&&datos2.tablero[1]==3&&datos2.tablero[2]==3&&datos2.tablero[3]==3&&datos2.tablero[4]==3&&datos2.tablero[5]==3&&datos2.tablero[6]==3){
             this.setVisible(false);
         String iconoUsar="trofeo.png";
         ImageIcon icono = new ImageIcon(iconoUsar);
        if(datos1.getPuntaje()>datos2.getPuntaje()){
            JOptionPane.showMessageDialog(null, "El ganador es "+jLabel2.getText()+"!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }else if(datos1.getPuntaje()<datos2.getPuntaje()){
        JOptionPane.showMessageDialog(null, "El ganador es "+jLabel3.getText()+"!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }else{
        JOptionPane.showMessageDialog(null, "Empate!", "Ganador!", JOptionPane.INFORMATION_MESSAGE,icono);
        }
        this.dispose();
            
            }
            
            
    }
    
   public void setjLabel1(String nombre) {
       
         jLabel1.setText(nombre);
    }
    
      public void setjLabel2(String nombre) {
       
         jLabel2.setText(nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Jugador 1");

        jLabel2.setText("Jugador 2");

        jLabel3.setText("Turno");

        jLabel4.setText("1");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dardo.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("D1");

        jLabel6.setText("D2");

        jLabel7.setText("D3");

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reiniciar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Resultados");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jButton7)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jButton6))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //inicio
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Inicio inicio= new Inicio();
        inicio.setSize(400, 400);
        inicio.setVisible(true);
         this.setVisible(false);
         inicio.setjTextField1(this.jLabel1.getText());
         inicio.setjTextField2(this.jLabel2.getText());
    }//GEN-LAST:event_jMenu1MouseClicked

    
    public void sumar2(){
         puntos=obtencionPuntos();
        datos2.setPuntaje(datos2.getPuntaje()+Integer.valueOf(puntos));
    }
    //reinicio
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
         jLabel4.setText("1");
         CuentaBoton=0;
         turno=1;
         datos1=new Datos();
         datos2=new Datos();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Resultados resultados= new Resultados();
        resultados.setSize(400, 500);
        resultados.setVisible(true);
          resultados.setjLabel1(jLabel1.getText());
         
         resultados.setjLabel2(jLabel2.getText());
         resultados.setjLabel31(Integer.toString(datos1.getPuntaje()));
         resultados.setjLabel32(Integer.toString(datos2.getPuntaje()));
         
          if(datos1.tablero[0]>=3||datos1.tablero[1]>=3||datos1.tablero[2]>=3||datos1.tablero[3]>=3||datos1.tablero[4]>=3||datos1.tablero[5]>=3||datos1.tablero[6]>=3||
               datos2.tablero[0]>=3||datos2.tablero[1]>=3||datos2.tablero[2]>=3||datos2.tablero[3]>=3||datos2.tablero[4]>=3||datos2.tablero[5]>=3||datos2.tablero[6]>=3){
              
                  datos1.tablero[0]=3;
                  datos1.tablero[1]=3;
                     datos1.tablero[3]=3;
                    datos1.tablero[4]=3;
                    datos1.tablero[5]=3;
                      datos1.tablero[6]=3;
        
                datos2.tablero[0]=3;
                  datos2.tablero[1]=3;
                 datos2.tablero[3]=3;
                    datos2.tablero[4]=3;
                    datos2.tablero[5]=3;
                    datos2.tablero[6]=3;
          }
         
         resultados.setjLabel10(Integer.toString(datos1.tablero[0]));
         resultados.setjLabel11(Integer.toString(datos1.tablero[1]));
         resultados.setjLabel12(Integer.toString(datos1.tablero[2]));
         resultados.setjLabel13(Integer.toString(datos1.tablero[3]));
         resultados.setjLabel14(Integer.toString(datos1.tablero[4]));
         resultados.setjLabel15(Integer.toString(datos1.tablero[5]));
         resultados.setjLabel16(Integer.toString(datos1.tablero[6]));
         
         resultados.setjLabel25(Integer.toString(datos2.tablero[0]));
         resultados.setjLabel26(Integer.toString(datos2.tablero[1]));
         resultados.setjLabel27(Integer.toString(datos2.tablero[2]));
         resultados.setjLabel28(Integer.toString(datos2.tablero[3]));
         resultados.setjLabel18(Integer.toString(datos2.tablero[4]));
         resultados.setjLabel30(Integer.toString(datos2.tablero[5]));
         resultados.setjLabel20(Integer.toString(datos2.tablero[6]));
         
    }//GEN-LAST:event_jMenu3MouseClicked

    
    //los 6 botones de dardos de cada jugador
    //botones jugador 1
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]==3 && datos2.tablero[0]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[0]<=3){
            
                datos1.tablero[0]=datos1.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]==3 && datos2.tablero[1]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[1]<=3){
            
                datos1.tablero[1]=datos1.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]==3 && datos2.tablero[2]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[2]<=3){
            
                datos1.tablero[2]=datos1.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]==3 && datos2.tablero[3]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[3]<=3){
            
                datos1.tablero[3]=datos1.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]==3 && datos2.tablero[4]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[4]<=3){
            
                datos1.tablero[4]=datos1.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]==3 && datos2.tablero[5]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[5]<=3){
            
                datos1.tablero[5]=datos1.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]==3 && datos2.tablero[6]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[6]<=3){
            
                datos1.tablero[6]=datos1.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton1.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
           activarBotones();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]==3 && datos2.tablero[0]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[0]<=3){
            
                datos1.tablero[0]=datos1.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]==3 && datos2.tablero[1]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[1]<=3){
            
                datos1.tablero[1]=datos1.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]==3 && datos2.tablero[2]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[2]<=3){
            
                datos1.tablero[2]=datos1.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]==3 && datos2.tablero[3]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[3]<=3){
            
                datos1.tablero[3]=datos1.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]==3 && datos2.tablero[4]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[4]<=3){
            
                datos1.tablero[4]=datos1.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]==3 && datos2.tablero[5]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[5]<=3){
            
                datos1.tablero[5]=datos1.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]==3 && datos2.tablero[6]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[6]<=3){
            
                datos1.tablero[6]=datos1.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton2.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
           activarBotones();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]==3 && datos2.tablero[0]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[0]<=3){
            
                datos1.tablero[0]=datos1.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]==3 && datos2.tablero[1]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[1]<=3){
            
                datos1.tablero[1]=datos1.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]==3 && datos2.tablero[2]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[2]<=3){
            
                datos1.tablero[2]=datos1.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]==3 && datos2.tablero[3]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[3]<=3){
            
                datos1.tablero[3]=datos1.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]==3 && datos2.tablero[4]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[4]<=3){
            
                datos1.tablero[4]=datos1.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]==3 && datos2.tablero[5]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[5]<=3){
            
                datos1.tablero[5]=datos1.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]==3 && datos2.tablero[6]!=3){
                sumar1(puntos);
            }else if(datos1.tablero[6]<=3){
            
                datos1.tablero[6]=datos1.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton3.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
          activarBotones();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //botones jugador2
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]!=3 && datos2.tablero[0]==3){
                sumar2(puntos);
            }else if(datos2.tablero[0]<=3){
            
                datos2.tablero[0]=datos2.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]!=3 && datos2.tablero[1]==3){
                sumar2(puntos);
            }else if(datos2.tablero[1]<=3){
            
                datos2.tablero[1]=datos2.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]!=3 && datos2.tablero[2]==3){
                sumar2(puntos);
            }else if(datos2.tablero[2]<=3){
            
                datos2.tablero[2]=datos2.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]!=3 && datos2.tablero[3]==3){
                sumar2(puntos);
            }else if(datos2.tablero[3]<=3){
            
                datos2.tablero[3]=datos2.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]!=3 && datos2.tablero[4]==3){
                sumar2(puntos);
            }else if(datos2.tablero[4]<=3){
            
                datos2.tablero[4]=datos2.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]!=3 && datos2.tablero[5]==3){
                sumar2(puntos);
            }else if(datos2.tablero[5]<=3){
            
                datos2.tablero[5]=datos2.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]!=3 && datos2.tablero[6]==3){
                sumar2(puntos);
            }else if(datos2.tablero[6]<=3){
            
                datos2.tablero[6]=datos2.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton5.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
           activarBotones();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]!=3 && datos2.tablero[0]==3){
                sumar2(puntos);
            }else if(datos2.tablero[0]<=3){
            
                datos2.tablero[0]=datos2.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]!=3 && datos2.tablero[1]==3){
                sumar2(puntos);
            }else if(datos2.tablero[1]<=3){
            
                datos2.tablero[1]=datos2.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]!=3 && datos2.tablero[2]==3){
                sumar2(puntos);
            }else if(datos2.tablero[2]<=3){
            
                datos2.tablero[2]=datos2.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]!=3 && datos2.tablero[3]==3){
                sumar2(puntos);
            }else if(datos2.tablero[3]<=3){
            
                datos2.tablero[3]=datos2.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]!=3 && datos2.tablero[4]==3){
                sumar2(puntos);
            }else if(datos2.tablero[4]<=3){
            
                datos2.tablero[4]=datos2.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]!=3 && datos2.tablero[5]==3){
                sumar2(puntos);
            }else if(datos2.tablero[5]<=3){
            
                datos2.tablero[5]=datos2.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]!=3 && datos2.tablero[6]==3){
                sumar2(puntos);
            }else if(datos2.tablero[6]<=3){
            
                datos2.tablero[6]=datos2.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton7.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
           activarBotones();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            
        puntos = obtencionPuntos();
        tipo=Acierto();
        if(puntos.equals("centro")){
            
            if(datos1.tablero[0]!=3 && datos2.tablero[0]==3){
                sumar2(puntos);
            }else if(datos2.tablero[0]<=3){
            
                datos2.tablero[0]=datos2.tablero[0]+tipo;
            
            }else{}
            
        }else if(puntos.equals("20")){
        
            if(datos1.tablero[1]!=3 && datos2.tablero[1]==3){
                sumar2(puntos);
            }else if(datos2.tablero[1]<=3){
            
                datos2.tablero[1]=datos2.tablero[1]+tipo;
            
            }else{}
            
        }else if(puntos.equals("19")){
        
            if(datos1.tablero[2]!=3 && datos2.tablero[2]==3){
                sumar2(puntos);
            }else if(datos2.tablero[2]<=3){
            
                datos2.tablero[2]=datos2.tablero[2]+tipo;
            
            }else{}
            
        }else if(puntos.equals("18")){
            
         if(datos1.tablero[3]!=3 && datos2.tablero[3]==3){
                sumar2(puntos);
            }else if(datos2.tablero[3]<=3){
            
                datos2.tablero[3]=datos2.tablero[3]+tipo;
            
            }else{}
        }else if(puntos.equals("17")){
            
         if(datos1.tablero[4]!=3 && datos2.tablero[4]==3){
                sumar2(puntos);
            }else if(datos2.tablero[4]<=3){
            
                datos2.tablero[4]=datos2.tablero[4]+tipo;
            
            }else{}
        }else if(puntos.equals("16")){
        
             if(datos1.tablero[5]!=3 && datos2.tablero[5]==3){
                sumar2(puntos);
            }else if(datos2.tablero[5]<=3){
            
                datos2.tablero[5]=datos2.tablero[5]+tipo;
            
            }else{}
            
        }else if(puntos.equals("15")){
        
             if(datos1.tablero[6]!=3 && datos2.tablero[6]==3){
                sumar2(puntos);
            }else if(datos2.tablero[6]<=3){
            
                datos2.tablero[6]=datos2.tablero[6]+tipo;
            
            }else{}
            
        }
         CuentaBoton=CuentaBoton+1;
         jButton6.setEnabled(false);
         
        if(CuentaBoton==6){
            turno=turno+1;
            CuentaBoton=0;
           activarBotones();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
